name: aboutcode-data
remote_root_url: https://github.com/aboutcode-data
description: Config for AboutCode package metadata federation.
documentation_url: null
data_license: null
data_maintainers:
  - name: Ayan Mahapatra
    email: asmahapatra@aboutcode.org
  - name: Jonathan Yang
    email: jyang@aboutcode.org
  - name: Keshav Priyadarshi
    email: kpriyadarshi@aboutcode.org
  - name: Philippe Ombredanne
    email: pombredanne@aboutcode.org
data_clusters:
  - data_kind: purls
    datafile_path_template: '{namespace}/{name}/purls.yml'
    purl_type_configs:
      - purl_type: github
        number_of_repos: 128
        number_of_dirs: 1024
      - purl_type: npm
        number_of_repos: 128
        number_of_dirs: 1024
      - purl_type: golang
        number_of_repos: 16
        number_of_dirs: 1024
      - purl_type: maven
        number_of_repos: 16
        number_of_dirs: 1024
      - purl_type: nuget
        number_of_repos: 16
        number_of_dirs: 1024
      - purl_type: perl
        number_of_repos: 16
        number_of_dirs: 1024
      - purl_type: php
        number_of_repos: 16
        number_of_dirs: 1024
      - purl_type: pypi
        number_of_repos: 16
        number_of_dirs: 1024
      - purl_type: ruby
        number_of_repos: 16
        number_of_dirs: 1024
      - purl_type: alpm
        number_of_repos: 4
        number_of_dirs: 1024
      - purl_type: bitbucket
        number_of_repos: 4
        number_of_dirs: 1024
      - purl_type: cargo
        number_of_repos: 4
        number_of_dirs: 1024
      - purl_type: cocoapods
        number_of_repos: 4
        number_of_dirs: 1024
      - purl_type: composer
        number_of_repos: 4
        number_of_dirs: 1024
      - purl_type: deb
        number_of_repos: 4
        number_of_dirs: 1024
      - purl_type: docker
        number_of_repos: 4
        number_of_dirs: 1024
      - purl_type: gem
        number_of_repos: 4
        number_of_dirs: 1024
      - purl_type: generic
        number_of_repos: 4
        number_of_dirs: 1024
      - purl_type: huggingface
        number_of_repos: 4
        number_of_dirs: 1024
      - purl_type: mlflow
        number_of_repos: 4
        number_of_dirs: 1024
      - purl_type: pub
        number_of_repos: 4
        number_of_dirs: 1024
      - purl_type: rpm
        number_of_repos: 4
        number_of_dirs: 1024
      - purl_type: default
        number_of_repos: 1
        number_of_dirs: 1024
    data_schema_url: null
    description: 'List of fully qualified PURL strings for a package, sorted by version.'
    documentation_url: 'https://github.com/package-url/purl-spec/'
    data_license: CC-BY-4.0
    data_maintainers: []
